---
name: Documentation improvement
description: Make documentation better by suggesting an improvement or pointing out a problem
title: "[DOCS] "
labels: documentation

body:
- type: textarea
  attributes:
    label: 📖 Documentation improvement
    description: |
      A clear and concise description of the improvement or problem.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the issue here.
  validations:
    required: false
...
