name: Delete old untagged images
on:
  schedule:
    - cron: '0 8 * * 1'
jobs:
  remove-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 scripts/remove_old_images.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
